#!/bin/sh

#stop processes on kill
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

_Workspaces() {
        al=$(xprop -root _NET_DESKTOP_NAMES | sed 's/.*= //' | tr -d ',"')
        ind=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
        curr=$(printf "%s" "$al" | cut -d " " -f$((ind+1)))
        printf "%s" "$al"| sed -e "s/$curr/%{R} $curr %{R}/"
}

_Modules() {
        while true; do
                echo "B:$("$HOME"/.config/leftwm/themes/epitaph/scripts/lemonbar/battery)"
                echo "C:$("$HOME"/.config/leftwm/themes/epitaph/scripts/lemonbar/cpu_usage)"
                echo "R:$("$HOME"/.config/leftwm/themes/epitaph/scripts/lemonbar/ram_usage)"
                echo "S:$(/usr/sbin/iwgetid -r || printf '%s' 'Disconnected')"
                echo "T:$("$HOME"/.config/leftwm/themes/epitaph/scripts/lemonbar/time)"
                echo "V:$(amixer get Master | awk -F'[][]' 'END{ print $2 }')"
                sleep 1
        done
}

_Wininfo() {
        leftwm-state | while read -r line; do
                echo "W:$(xdotool getwindowfocus getwindowname | cut -c 1-30)"
                echo "K:$(_Workspaces)"
        done
}

lemon_fifo="/tmp/lemonfifo"

[ -e "$lemon_fifo" ] && rm "$lemon_fifo"
mkfifo "$lemon_fifo"

_Modules > "$lemon_fifo" &
_Wininfo > "$lemon_fifo" &

_Main() {
        while read -r report; do
                case $report in
                        B*) batt="$(echo "$report" | cut -d':' -f2-)";;
                        C*) cpu="$(echo "$report" | cut -d':' -f2-)";;
                        K*) wm="$(echo "$report" | cut -d':' -f2-)";;
                        R*) ram="$(echo "$report" | cut -d':' -f2-)";;
                        S*) ssid="$(echo "$report" | cut -d':' -f2-)";;
                        T*) time="$(echo "$report" | cut -d':' -f2-)";;
                        V*) vol="$(echo "$report" | cut -d':' -f2-)";;
                        W*) wname="$(echo "$report" | cut -d':' -f2-)";;
                esac
                sleep 0.1s
                printf "%s" "%{F#FAFAFA} $wm | $wname %{r} %{F#E5C07B} 龍 cpu: $cpu %{F#FAFAFA}| %{F#E06c75}  ram: $ram %{F#FAFAFA}|%{F#61AFEF}  $time %{F#FAFAFA}|%{F#98C379}  %{F#FAFAFA}$batt | 墳 $vol |%{F#c678dd}  $ssid "
        done
}

_Main < "$lemon_fifo"
