#!/bin/sh

SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

feh --bg-scale "$SCRIPTPATH"/reset.jpg

leftwm-command "UnloadTheme"

for process in picom battery-notify wallpaper dunst; do
    pgrep -x "$process" > /dev/null && pkill "$process"
done
