#!/bin/sh

SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH"/reset.jpg
fi

echo "UnloadTheme" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe
pkill picom
pkill battery-notify
pkill wallpaper
