#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH"/reset.jpg
fi

echo "UnloadTheme" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe

# Don't kill with ampersand, let killing processes block state to ensure
# nothing gets messed up in --experimental-backends the process.
pkill picom
pkill compton
pkill nm-applet
pkill blueman-applet
pkill polybar
pkill xfce4-power-manager
pkill seahorse-daemon
pkill gnome-keyring-daemon
pkill alacritty
pkill flameshot
