#!/bin/bash
set -euo pipefail

compile_modules() {
    echo "Compiling utilities..."
    rustc ./scripts/battery-notify.rs -C codegen-units=1 -C opt-level=z -C lto -C panic=abort -C target-cpu=native --edition=2021 -o ./scripts/battery-notify
}

helpme() {
    echo "Epitaph - Leftwm Epitaph Install Script
    Usage: epitaph [option]
    Options:
    install - Checks for dependencies and installs Epitaph.
    recompile - Recompiles the power manager (battery-notify).
    help - Show this message"
    exit 0
}

main() {
    local FILE="$HOME/.config/leftwm/themes/Epitaph/.installed"

    if [[ -f "$FILE" ]]; then
        echo "Epitaph is already installed. If you want to rebuild the
power manager please invoke this script with the 'recompile' option. Or
at your own risk, you can remove the '.installed' file in your Epitaph theme"
        exit 0
    fi

    echo "Copying the Epitaph configuration file to your leftwm configuration file"
    cp ~/.config/leftwm/config.ron ~/.config/leftwm/config.ron.bak
    cp ./config.ron ~/.config/leftwm/config.ron
    echo "File copied successfully"
    echo "Your previous config has been saved as ~/.config/leftwm/config.ron.bak"

    echo "Copying the Epitaph's rofi configuration file to your configuration directory"
    if [ ! -d "$HOME"/.config/rofi ]; then
        mkdir -p "$HOME"/.config/rofi
    fi

    cp ./config.rasi "$HOME"/.config/rofi/config.rasi
    echo "Copying fonts to local dir..."
    cp -R ./fonts "$HOME"/.local/share/fonts
    fc-cache -fv

    c=0;
    n=0;
    reqs=(leftwm rofi i3lock i3lock-fancy tilix rustc picom feh mate-polkit\
    pulseaudio notify-send gnome-keyring polybar playerctl pamixer thunar\
    tumbler ffmpegthumbnailer)

    recommended=(flatpak xdg-user-dirs-gtk mate-polkit blueman-applet)

    for p in "${reqs[@]}"; do
        if command -v "$p" &>/dev/null
        then
            echo -e "[\e[32mOK\e[39m] $p is installed!"
            (( c++ )) || true
        else
            echo -e "[\e[31mERROR\e[39m] $p is NOT installed!"
            (( n++ )) || true
        fi
    done

    printf "%d of %d requirements were found.\n"  "$c" "${#reqs[@]}"
    printf "%d of %d requirements are missing\n" "$n" "${#reqs[@]}"
    echo "The following apps are recommended:" "${recommended[@]}"

    if [[ n -gt 1  ]]; then
        echo "Missing binaries were detected! Try installing them re-run this script after that."
        exit 1
    fi
    compile_modules;
    touch "$FILE"
    echo "==== INSTALLATION COMPLETE ===="
    echo "If you did the installation correctly there are a few additional steps\
        you must follow to get Epitaph up and running:

              1 - [Optional] Install the recommended packages printed down here for a better out of the box experience.
              2 - Read the Wiki for full customization options: https://github.com/VentGrey/Epitaph/wiki
              3 - Help me improve this script by giving me your suggestions, ideas are always welcome!
              4 - Confusion will be your epitaph (https://www.youtube.com/watch?v=vXrpFxHfppI)

              EXTRAS:
              - Consider sponsoring this theme or giving it a star. Your help means a lot to me! <3
              - Consider giving Leftwm a star on GitHub or contribute to their work.

    IMPORTANT: You'll need to reload leftwm or restart your OS for changes to work properly.
    This script will reload leftwm for you. If that doesn't work, try logging out and back in, if that doesn't work try your system. If that doesn't work either, please open a GitHub Issue because I did something clearly wrong."
    read -n 1 -s -r -p "Press any key to restart LeftWM"
    leftwm-command SoftReload
    exit 0
}

if [ $# -eq 0 ]; then
    helpme
fi

case "$1" in
    "install") main;;
    "recompile") compile_modules;;
    "help") helpme;;
    *) echo "Not a valid option"; helpme;
esac
