#!/bin/bash
compile_modules() {
    rustc ./scripts/battery-notify.rs -C codegen-units=1 -C strip=symbols -C opt-level=z -C lto -C panic=abort -C target-cpu=native --edition=2021 -o ./scripts/battery-notify
}

helpme() {
    echo "Epitaph - Leftwm + EpitaphWM Installation Script

    Usage: ./epitaph [option]

    Options:
    install     Checks for dependencies and installs Epitaph.
    recompile   Recompiles the power manager (battery-notify).
    help        Show this message"
    exit 0
}

main() {
    if [[ -f "$HOME/.config/leftwm/themes/Epitaph/.installed" ]]; then
        echo "Epitaph is already installed. If you want to rebuild the
power manager please invoke this script with the 'recompile' option. Or
at your own risk, you can remove the '.installed' file in your Epitaph theme"
        exit 0
    fi

    echo "Copying the Epitaph configuration file to your leftwm configuration\
        file all of your previous config files will be copied with the same name and a .bak extension."
    cp ~/.config/leftwm/config.ron ~/.config/leftwm/config.ron.bak
    cp ./config.ron ~/.config/leftwm/config.ron
    mkdir -p "$HOME"/.config/rofi
    cp ./config.rasi "$HOME"/.config/rofi/config.rasi
    cp -R ./fonts "$HOME"/.local/share/fonts
    fc-cache -fv

    c=0;
    n=0;
    reqs=(leftwm rofi i3lock i3lock-fancy tilix rustc picom feh mate-polkit pulseaudio notify-send gnome-keyring\
        polybar playerctl pamixer thunar tumbler ffmpegthumbnailer xdg-user-dirs mate-polkit blueman-applet
         xss-lock)

    for p in "${reqs[@]}"; do
        if command -v "$p" &>/dev/null
        then
            echo -e "[\e[32mOK\e[39m] $p is installed!"
            (( c++ )) || true
        else
            echo -e "[\e[31mERROR\e[39m] $p is NOT installed!"
            (( n++ )) || true
        fi
    done

    printf "%d of %d requirements were found.\n"  "$c" "${#reqs[@]}"
    printf "%d of %d requirements are missing\n" "$n" "${#reqs[@]}"

    if [[ n -gt 1  ]]; then
        echo "Missing binaries were detected! Try installing them re-run this script after that."
        exit 1
    fi

    compile_modules;
    touch "$FILE"
    echo "==== INSTALLATION COMPLETE ===="
    echo "Here are some additional steps for you\

              1 - [Optional] Install the recommended packages listed on the wiki for a better out of the box experience.
              2 - Read the Wiki for full customization options: https://github.com/VentGrey/Epitaph/wiki

    IMPORTANT: You'll need to reload leftwm or restart your OS for changes to work properly.
    This script will reload leftwm for you. If that doesn't work, try logging out and back in, if that doesn't work try your system. If that doesn't work either, please open a GitHub Issue because I did something clearly wrong."
    read -n 1 -s -r -p "Press any key to restart LeftWM"
    leftwm-command SoftReload && exit 0
}

[ $# -eq 0 ] && helpme

case "$1" in
    "install") main;;
    "recompile") compile_modules;;
    "help") helpme;;
    *) echo "Not a valid option"; helpme;
esac
