.TH EPITAPH 1
.SH NAME
epitaph - Epitaph Theme Documentation
.SH DESCRIPTION
Epitaph is a complete theme for LeftWM. It is being developed as a starting point for users transitioning from a full-blown Desktop Environment to a standalone Window Manager.
This documentation is not a list of commands or flags, but rather a compilation of how some
scripts and configurations work, and how can you modify them to suit your own needs.
.SH SCRIPTS
Epitaph comes with the following scripts:
.\" Battery Notify section\"
.IP "battery-notify"
battery-notify is a POSIX sh script used for monitoring your battery and sending notifications based on its status. This script defines 9 variables for configuration purposes.
.sp
.I max-charge
It is used to determine what is the max charging value your battery has to be considered "full". It is recommended to set a value lower than 100 to avoid messing up your charging cycles.
.sp
.I low
It is used to determine when your battery charge can be considered "low" and as a first warning to plug in your system to charge.
.sp
.I critical
It is used to determine if your battery is VERY low.
.sp
.I dead
It is used as a "stopping" value to notify the user when the battery is WAY too low and immediate action is needed. It's recommended to set a value higher than 0 or 1 to avoid a full discharge and thus damaging the battery in the long run.
.sp
.I notified
is a variable used to track if the user has been notified at least once about it's system status. It's not recommended to change this value to other than zero.
.sp
.I sleep_time
is used to tell the script how much time should it wait (in seconds) before checking the battery status again. The lower the value the higher CPU / disk operations usage.
.sp
.I dead_action
is used to define what action should be taken when the system battery reaches the dead battery value. The default value is "suspend" and is used on a systemd command. If your init system is different, please change the full command accordingly.
.sp
.I battery
is the current system battery variable grabbed by the cat command. It is recommended to change this value as this differs from computer to computer. The author's computer uses BAT1 as main battery, if your computer uses BAT0 as the main battery you'll need to modify this script to work properly.
.sp
.I status
is the current system battery status (charge percentage). It is recommended to change this value as this differs from computer to computer. The author's computer uses BAT1 as main battery, if your computer uses BAT0 as the main battery you'll need to modify this script to work properly.
.\" Battery Notify section\"

.\" cmustatus section\"
.IP "cmustatus"
This script is used by the polybar.config file to display your current playing song in cmus.
.\" cmustatus section\"

.\" lock section\"
.IP "lock"
This script is called by the up script and it is used to lock the screen using i3lock-fancy. If you wish to change your screenlock program with anything else please modify the 5th line of this script.
.\" lock section\"

.\" wallpaper section\"
.IP "wallpaper"
This script uses feh to change randomly the current epitaph wallpaper every 10 minutes from the wallpapers/ directory. If you want to add new wallpapers place it in the wallpapers directory and name it accordingly, most image formats are supported, if you want to modify the wallpaper change time just change the sleep command.
.\" wallpaper section\"

.SH DMENU SCRIPTS
These are scripts that use dmenu as a frontend and are one of the main reasons to use Epitaph as your leftwm theme :)

.\" applist section\"
.IP "applist"
This script acts as your "launcher" menu similar to other Desktop Environments or window managers. Applist reads a file at $HOME/.local/bin/applist and follows the following syntax:
.br
.B "<modifier> <command>     #<readable name> <icon>"
For the sake of example, an applist entry should look like this:
.br
.B "gimp  # GIMP "
.br
If you wish to launch a terminal command you should use the
.B TERMINAL
modifier (in caps). For example:
.br
.B "TERMINAL htop  # htop system monitor "
.br
Applist has dmenu as a dependency and requires two variables to be set:
.sp
.I TERMINAL
is a variable used to tell applist which terminal emulator should it use to launch terminal specific applications. The default value for this is kitty (https://github.com/kovidgoyal/kitty). If you don't use kitty you should change this value for any terminal emulator you like.
.sp
.I TERMINAL_TITLE
is a variable used to specify the title tag for your terminal emulator which will be displayed on the top polybar panel. Most terminal emulators support this flag, make sure yours does. If yours doesn't, change this flag to a supported one or delete it completely.
.sp
Applist also comes with a special function called
.B flrun
used to run flatpak apps. This is because launching a flatpak app from the command line is verbose and pasting that order in Applist would be a long one liner. This function is used to shorten the flatpak syntax to a more compact order for it to run:
.br
.B "flrun md.obsidian.Obsidian                   # Obsidian ﴬ"
.br
As extra info, Applist detects binaries in your home folder if they are registered in the $PATH variable.
.sp
If you don't know how to start writing your appfile, the install script can download + install one for you if you wish.
.\" applist section\"

.\" manpages section\"
.IP "manpages"
WIP
.\" manpages section\"


.\" power-menu section\"
.IP "power-menu"
WIP
.\" power-menu section\"

.SH Switching from polybar <---> lemonbar.
If you'd like to use polybar instead of lemonbar just edit the up script, located at the root of the epitaph theme and change the following variable:
.I use_polybar=0
to
.I use_polybar=1

.SH Customizing Lemonbar
It is recommended that you use the lemonbar-xft fork as some

.SH Editing lemonbar scripts / programs
