.TH EPITAPH 1
.SH NAME
epitaph - Epitaph Theme Documentation
.SH DESCRIPTION
Epitaph is a complete theme for LeftWM. It is being developed as a starting point for users transitioning from a full blown Desktop Environment to a standalone Window Manager.
This documentation is not a list of commands or flags, but rather a compilation of how some
scripts and configurations work, and how can you modify them to suit your own needs.
