#!/bin/bash

c=0;
n=0;
reqs=(leftwm polybar picom feh xdg-user-dirs-update\
    mate-polkit gnome-keyring-daemon aa-notify blueman-applet\
    nm-applet pulseaudio notify-send xrandr i3lock i3lock-fancy dmenu)

recommended=(kitty flatpak thunar)

    for p in "${reqs[@]}"; do
        if command -v "$p" &>/dev/null
        then
            echo -e "[\e[32mOK\e[39m] $p is installed!"
            (( c++ )) || true
        else
            echo -e "[\e[31mERROR\e[39m] $p is NOT installed!"
            (( n++ )) || true
        fi
    done

    printf "%d of %d requirements were found.\n"  "$c" "${#reqs[@]}"
    printf "%d of %d requirements are missing\n" "$n" "${#reqs[@]}"

    echo "Requirements check complete."
    echo "If you did the installation correctly there are a few additional
         steps you must follow to get Epitaph up and running:

         1 - [Optional] Install the recommended packages printed down here
         2 - Customize your terminal in the applist and manpages script
         3 - Customize your applist
         4 - Open bugs in GitHub :D
        "

    echo "The following apps are recommended:" "${recommended[@]}"

    exit 0
