#!/bin/sh
export SCRIPTPATH

SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s "$SCRIPTPATH/down" "/tmp/leftwm-theme-down"

if ! pgrep -x "picom" > /dev/null
then
    nohup picom --config "$SCRIPTPATH"/picom/picom.conf > /dev/null 2>&1 &
else
    pkill picom
    nohup picom --config "$SCRIPTPATH"/picom/picom.conf > /dev/null 2>&1 &
fi

#set background using the wallpaper script
if [ -d "$SCRIPTPATH"/wallpapers ]; then
    if ! pgrep -x "wallpaper" > /dev/null
    then
        nohup "$SCRIPTPATH"/scripts/wallpaper 2>&1 &
    else
        pkill wallpaper
        nohup "$SCRIPTPATH"/scripts/wallpaper 2>&1 &
    fi
else
    feh --bg-scale "$SCRIPTPATH"/background.jpeg 2>&1 &
fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# ====[ AUTOSTART ] ====
# Start custom power management notifications
if ! pgrep -x "battery-notify" > /dev/null
then
    nohup "$SCRIPTPATH"/scripts/battery-notify 2>&1 &
else
    pkill battery-notify
    nohup "$SCRIPTPATH"/scripts/battery-notify 2>&1 &
fi

# ==== [ BAR CONFIGURATIONS ] ====
pkill polybar;
if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar -c "$SCRIPTPATH/polybar.config" mainbar > /dev/null &
    done
else
    polybar --reload "$SCRIPTPATH/polybar.config" mainbar > /dev/null &
fi
