#!/bin/sh

len=$(xdotool getwindowfocus getwindowname | wc -m)
max_len=30
if [ "$len" -gt "$max_len" ];then
	echo "$(xdotool getwindowfocus getwindowname | cut -c 1-$max_len)..."
else
	xdotool getwindowfocus getwindowname
fi
