#!/usr/bin/perl

# Set a default value for the cpu usage
my $cpu_usage = -1;

open (MPSTAT, 'mpstat 1 1 |') or die;
while (<MPSTAT>) {
    if (/^.*\s+(\d+\.\d+)[\s\x00]?$/) {
        $cpu_usage = 100 - $1; # 100% - %idle
        last;
    }
}
close(MPSTAT);

$cpu_usage eq -1 and die 'Can\'t find CPU information';
printf "%.0f%%\n", $cpu_usage;
