#!/bin/sh

terminal="kitty"

manual="$(man -k . | dmenu -p Manual: -l 10 | awk '{print $2 " " $1}'\
    | tr -d '()')"

if [ -n "$manual" ]; then
    # shellcheck disable=SC2086
    "$terminal" -e -T "Manual Reader - 📕 Reading: $manual" man $manual
fi
