#!/bin/sh

option=$(printf " Shutdown\n Reboot\n鈴 Suspend\n Logout\n" \
    | dmenu -l 10 -p "Power Menu: ")

case $option in
    " Shutdown") pkexec poweroff ;;
    " Reboot") pkexec reboot ;;
    "鈴 Suspend") pkexec zzz;;
    " Logout") loginctl terminate-session "${XDG_SESSION_ID-}";;
    "") exit 0;;
    *) notify-send "What are you trying to do?"\
        "Son, this is a power menu" --icon=face-worried
esac
