#!/bin/sh

option=$(printf " Shutdown\n Reboot\n鈴 Suspend\n Logout\n" \
    | dmenu -l 10 -p "Power Menu: ")

case $option in
    " Shutdown") dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop ;;
    " Reboot") dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart ;;
    "鈴 Suspend") dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Suspend;;
    " Logout") loginctl terminate-session "${XDG_SESSION_ID-}";;
    "") exit 0;;
    *) notify-send "What are you trying to do?"\
        "Son, this is a power menu" --icon=face-worried
esac
