#!/bin/sh

OPTIONS="\
🌎 latam
🇪🇸 es
🇬🇧 us"

CHOICE=$(echo "$OPTIONS" | rofi -dmenu -p "Select your keyboard distribution" | awk '{print $2 $3}')

case $CHOICE in
  latam)
    setxkbmap latam
    ;;
  es)
    setxkbmap es
    ;;
  us)
    setxkbmap us -variant intl
    ;;
  *)
    notify-send "Invalid keyboard selection or exited script"
    exit 1
    ;;
esac
