#!/bin/sh

# Script idea taken and modified from:
# https://www.reddit.com/r/i3wm/comments/

# Default values when battery level is low or critical
max_charge=98
low=15
critical=5
dead=2

# Notified boolean (DO NOT CHANGE)
notified=0

# Sleep time to run this script again
sleep_time=5

# Actions to perform when reaching the "dead" level
dead_action="suspend"

while true ; do
    # Get battery level from system
    battery=$(cat /sys/class/power_supply/BAT1/capacity)
    status=$(cat /sys/class/power_supply/BAT1/status)

    if [ "$status" = "Discharging" ]; then
        # check if battery is below the low level
        if [ "$battery" -gt $critical ] && [ "$battery" -le $low ]\
            && [ $notified -eq 0 ] ; then
            notify-send 'Low battery!' 'Connect to power to avoid losing data'\
                --icon=battery-low
            notified=$((notified+1))
        # Check if user ignored the original warning
        elif [ "$battery" -le $critical ]; then
            notify-send 'Very low battery!'\
                'Connect to power immediately, shutdown or face data loss!'\
                --icon=battery-low
        elif [ "$battery" -le $dead ]; then
            notify-send 'Battery is about to die'\
                'Suspending gracefully to avoid data loss.' --icon=battery-low
            notified=$((notified-1))
            execommand="systemctl $dead_action"
            eval "$execommand"
        fi
    elif [ "$status" = "Charging" ]; then
        if [ "$battery" -ge $max_charge ] && [ $notified -eq 0 ]; then
            notify-send 'Battery fully charged' --icon=battery
            notified=$((notified+1))
        fi
    else
        notified=$((notified-1))
    fi
    sleep $sleep_time
done

exit 0
