name: check_shell_scripts
on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  check_shell_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: installShellCheck
        run: sudo apt install shellcheck
      - name: check scripts
        run: shellcheck up down scripts/songstatus scripts/wallpaper scripts/rofi/power-menu